version: '3.8'

services:
  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:80"

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:80"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/entrypoint.sh:/entrypoint.sh
    entrypoint: ["sh", "/entrypoint.sh"]
    depends_on:
      - app_blue
      - app_green
