version: '3.8'

services:
  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:80"

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:80"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
